#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = configure ]; then
    adduser \
        --force-badname \
        --gecos "Flatpak system-wide installation helper" \
        --group \
        --home /nonexistent \
        --no-create-home \
        --quiet \
        --system \
        _flatpak

    # Run a do-nothing command (it just lists configured remotes) for
    # its side-effect of initializing the shared system-wide repository.
    flatpak remote-list --system >/dev/null || :

    # Enable rewrite-launchers user service on first install only,
    # if it has not been enabled before.
    if [ -z "${DPKG_ROOT:-}" ] ; then
		deb-systemd-helper --user unmask 'xdg-desktop-portal-rewrite-launchers.service' >/dev/null || true
		# was-enabled defaults to true, so new installations run enable.
		if deb-systemd-helper --quiet --user was-enabled 'xdg-desktop-portal-rewrite-launchers.service' ; then
			deb-systemd-helper --user enable 'xdg-desktop-portal-rewrite-launchers.service' >/dev/null || true
		fi
	fi
fi

exit 0

# vim:set sw=4 sts=4 et:
